export const projects = [
	{
		id: 1,
		name: "Weather App",
		description: "App to see weather in real-time and search for cities.",
		technologies: ["React", "Javascript", "CSS3"],
		stack: "Frontend",
		github: "https://github.com/lioarce01/weather-react-app",
		deploy: "https://react-weather-app-lioarce1.vercel.app",
		image: "https://i.postimg.cc/t4k6ZN1x/weather.png",
	},
	{
		id: 2,
		name: "Cloud Management",
		description: "Frontend of a Cloud Management Website.",
		technologies: ["React", "Javascript", "TailwindCSS"],
		stack: "Frontend",
		github: "https://github.com/lioarce01/cloud-react-app",
		deploy: "https://cloud-react-app-beta.vercel.app",
		image: "https://i.postimg.cc/MGZydFk5/cloud.png",
	},
	{
		id: 3,
		name: "Crypto Assets",
		description: "Frontend of a Crypto Assets Website.",
		technologies: ["React", "Javascript", "NextUI"],
		stack: "Frontend",
		github: "https://github.com/lioarce01/crypto-project-react-app",
		deploy: "https://crypto-project-react-app.vercel.app",
		image: "https://i.postimg.cc/RhtfWrfS/crypto.png",
	},
	{
		id: 4,
		name: "Pizza Restaurant",
		description: "Frontend of a Pizza Restaurant Website.",
		technologies: ["React", "Javascript", "Styled Components"],
		stack: "Frontend",
		github: "https://github.com/lioarce01/pizza-restaurant-react-app",
		deploy: "https://lioarce-restaurant-react-app.vercel.app",
		image: "https://i.postimg.cc/q77386nZ/pizza.png",
	},
	{
		id: 5,
		name: "Data Finance",
		description: "Frontend of a Datan Finances Website.",
		technologies: ["React", "Javascript", "TailwindCSS"],
		stack: "Frontend",
		github: "https://github.com/lioarce01/data-finance-react-app",
		deploy: "https://data-finance-react-app.vercel.app",
		image: "https://i.postimg.cc/1tfDZV3N/finance.png",
	},
	{
		id: 6,
		name: "Decentralized Trading",
		description: "Frontend of a Decentralized Trading App.",
		technologies: ["React", "Javascript", "TailwindCSS"],
		stack: "Frontend",
		github: "https://github.com/lioarce01/defi-react-app",
		deploy: "https://defi-react-app.vercel.app",
		image: "https://i.postimg.cc/CLykW1Tz/trading.png",
	},
	{
		id: 7,
		name: "Tesla Clone",
		description: "Tesla Clone Website.",
		technologies: ["React", "Javascript", "Styled Components"],
		stack: "Frontend",
		github: "https://github.com/lioarce01/tesla-clone-react",
		deploy: "https://teslaclone-lioarce-reactapp.vercel.app",
		image: "https://i.postimg.cc/wThLHpgF/tesla.png",
	},
	{
		id: 8,
		name: "Terminal Emulator",
		description: "A terminal emulator",
		technologies: ["React", "Javascript", "CSS3"],
		stack: "Frontend",
		github: "https://github.com/lioarce01/react-terminal",
		deploy: "https://react-terminal-la.vercel.app",
		image: "https://i.postimg.cc/Y9ZY22vD/terminal.png",
	},
	{
		id: 9,
		name: "Twitch Clone",
		description: "Twitch Clone using mock data",
		technologies: ["NextJs", "Javascript", "TailwindCSS"],
		stack: "Frontend",
		github: "https://github.com/lioarce01/twitch-next-app",
		deploy: "https://twitch-next-app.vercel.app",
		image: "https://i.postimg.cc/DwnswMzh/twitch.png",
	},
	{
		id: 10,
		name: "Crypto Hunter",
		description: "Cryptocurrency tracker with Price, Volume, Market Cap, etc.",
		technologies: ["NextJs", "Javascript", "Firebase", "TailwindCSS"],
		stack: "Frontend",
		github:
			"https://github.com/lioarce01/crypto-hunter/tree/main/src/components/Authentication",
		deploy: "https://crypto-hunter-app.vercel.app",
		image: "https://i.postimg.cc/RhtfWrfS/crypto.png",
	},
	{
		id: 11,
		name: "Netflix Clone",
		description: "Netflix clone fetching TMDB API",
		technologies: ["NextJs", "Typescript", "Firebase", "TailwindCSS"],
		stack: "Frontend",
		github: "https://github.com/lioarce01/movie-app/",
		deploy: "https://movieapp.lioarce01.vercel.app",
		image: "https://i.postimg.cc/Hx0GtnbF/netflix.png",
	},
	{
		id: 12,
		name: "Videogames SPA",
		description: "Videogames app to search, add, and delete games.",
		technologies: [
			"React/Redux",
			"Javascript",
			"CSS3",
			"NodeJs",
			"Express",
			"Sequelize",
			"PostgreSQL",
		],
		stack: "Fullstack",
		github: "https://github.com/lioarce01/PI-Henry-Videogames",
		deploy: "https://henry-videogames-pi.vercel.app",
		image: "https://i.postimg.cc/CK6fJMsM/videogames.png",
	},
	{
		id: 13,
		name: "Paws Founding",
		description:
			"A social platform combined with crowdfunding system to support animal shelters.",
		technologies: [
			"React/Redux",
			"Typescript",
			"Auth0",
			"NodeJs",
			"Express",
			"Prisma",
			"MongoDB",
			"Mercadopago API",
			"Nodemailer",
			"Leafleet",
			"TailwindCSS",
		],
		stack: "Fullstack",
		github: "https://github.com/lioarce01/PF-Henry-Grupo05",
		deploy: "https://pf-henry-grupo05.vercel.app",
		image: "https://i.postimg.cc/tRnFS6cK/paws.png",
	},
]
